[ { "id": 10001,
    "name": "Razer Mark of Precision",
    "type": "red",
    "tier": 3,
    "stat": "critical damage",
    "boost": 2.23
  },
  { "id": 10002,
    "name": "Razer Quintessence of Speed",
    "type": "quint",
    "tier": 3,
    "stat": "movement speed",
    "boost": 1.5
  },
  { "id": 5001,
    "name": "Lesser Mark of Attack Damage",
    "type": "red",
    "tier": 1,
    "stat": "attack damage",
    "boost": 0.53
  },
  { "id": 5002,
    "name": "Lesser Mark of Scaling Attack Damage",
    "type": "red",
    "tier": 1,
    "stat": "scaling attack damage",
    "boost": 0.08
  },
  { "id": 5003,
    "name": "Lesser Mark of Attack Speed",
    "type": "red",
    "tier": 1,
    "stat": "attack speed",
    "boost": 0.94
  },
  { "id": 5005,
    "name": "Lesser Mark of Critical Damage",
    "type": "red",
    "tier": 1,
    "stat": "critical damage",
    "boost": 1.24
  },
  { "id": 5007,
    "name": "Lesser Mark of Critical Chance",
    "type": "red",
    "tier": 1,
    "stat": "critical chance",
    "boost": 0.52
  },
  { "id": 5009,
    "name": "Lesser Mark of Armor Penetration",
    "type": "red",
    "tier": 1,
    "stat": "armor penetration",
    "boost": 0.72
  },
  { "id": 5011,
    "name": "Lesser Mark of Health",
    "type": "red",
    "tier": 1,
    "stat": "health",
    "boost": 1.93
  },
  { "id": 5012,
    "name": "Lesser Mark of Scaling Health",
    "type": "red",
    "tier": 1,
    "stat": "scaling health",
    "boost": 0.3
  },
  { "id": 5013,
    "name": "Lesser Mark of Armor",
    "type": "red",
    "tier": 1,
    "stat": "armor",
    "boost": 0.51
  },
  { "id": 5015,
    "name": "Lesser Mark of Magic Resist",
    "type": "red",
    "tier": 1,
    "stat": "magic resist",
    "boost": 0.43
  },
  { "id": 5016,
    "name": "Lesser Mark of Scaling Magic Resist",
    "type": "red",
    "tier": 1,
    "stat": "scaling magic resist",
    "boost": 0.04
  },
  { "id": 5021,
    "name": "Lesser Mark of Cooldown Reduction",
    "type": "red",
    "tier": 1,
    "stat": "cooldown reduction",
    "boost": -0.11
  },
  { "id": 5023,
    "name": "Lesser Mark of Ability Power",
    "type": "red",
    "tier": 1,
    "stat": "ability power",
    "boost": 0.33
  },
  { "id": 5024,
    "name": "Lesser Mark of Scaling Ability Power",
    "type": "red",
    "tier": 1,
    "stat": "scaling ability power",
    "boost": 0.06
  },
  { "id": 5025,
    "name": "Lesser Mark of Mana",
    "type": "red",
    "tier": 1,
    "stat": "mana",
    "boost": 3.28
  },
  { "id": 5026,
    "name": "Lesser Mark of Scaling Mana",
    "type": "red",
    "tier": 1,
    "stat": "scaling mana",
    "boost": 0.65
  },
  { "id": 5027,
    "name": "Lesser Mark of Mana Regeneration",
    "type": "red",
    "tier": 1,
    "stat": "mana regeneration",
    "boost": 0.15
  },
  { "id": 5029,
    "name": "Lesser Mark of Magic Penetration",
    "type": "red",
    "tier": 1,
    "stat": "magic penetration",
    "boost": 0.49
  },
  { "id": 5031,
    "name": "Lesser Glyph of Attack Damage",
    "type": "blue",
    "tier": 1,
    "stat": "attack damage",
    "boost": 0.16
  },
  { "id": 5032,
    "name": "Lesser Glyph of Scaling Attack Damage",
    "type": "blue",
    "tier": 1,
    "stat": "scaling attack damage",
    "boost": 0.02
  },
  { "id": 5033,
    "name": "Lesser Glyph of Attack Speed",
    "type": "blue",
    "tier": 1,
    "stat": "attack speed",
    "boost": 0.35
  },
  { "id": 5035,
    "name": "Lesser Glyph of Critical Damage",
    "type": "blue",
    "tier": 1,
    "stat": "critical damage",
    "boost": 0.31
  },
  { "id": 5037,
    "name": "Lesser Glyph of Critical Chance",
    "type": "blue",
    "tier": 1,
    "stat": "critical chance",
    "boost": 0.15
  },
  { "id": 5041,
    "name": "Lesser Glyph of Health",
    "type": "blue",
    "tier": 1,
    "stat": "health",
    "boost": 1.49
  },
  { "id": 5042,
    "name": "Lesser Glyph of Scaling Health",
    "type": "blue",
    "tier": 1,
    "stat": "scaling health",
    "boost": 0.3
  },
  { "id": 5043,
    "name": "Lesser Glyph of Armor",
    "type": "blue",
    "tier": 1,
    "stat": "armor",
    "boost": 0.39
  },
  { "id": 5045,
    "name": "Lesser Glyph of Magic Resist",
    "type": "blue",
    "tier": 1,
    "stat": "magic resist",
    "boost": 0.74
  },
  { "id": 5046,
    "name": "Lesser Glyph of Scaling Magic Resist",
    "type": "blue",
    "tier": 1,
    "stat": "scaling magic resist",
    "boost": 0.09
  },
  { "id": 5047,
    "name": "Lesser Glyph of Health Regeneration",
    "type": "blue",
    "tier": 1,
    "stat": "health regeneration",
    "boost": 0.15
  },
  { "id": 5051,
    "name": "Lesser Glyph of Cooldown Reduction",
    "type": "blue",
    "tier": 1,
    "stat": "cooldown reduction",
    "boost": -0.47
  },
  { "id": 5052,
    "name": "Lesser Glyph of Scaling Cooldown Reduction",
    "type": "blue",
    "tier": 1,
    "stat": "scaling cooldown reduction",
    "boost": -0.05
  },
  { "id": 5053,
    "name": "Lesser Glyph of Ability Power",
    "type": "blue",
    "tier": 1,
    "stat": "ability power",
    "boost": 0.66
  },
  { "id": 5054,
    "name": "Lesser Glyph of Scaling Ability Power",
    "type": "blue",
    "tier": 1,
    "stat": "scaling ability power",
    "boost": 0.1
  },
  { "id": 5055,
    "name": "Lesser Glyph of Mana",
    "type": "blue",
    "tier": 1,
    "stat": "mana",
    "boost": 6.25
  },
  { "id": 5056,
    "name": "Lesser Glyph of Scaling Mana",
    "type": "blue",
    "tier": 1,
    "stat": "scaling mana",
    "boost": 0.79
  },
  { "id": 5057,
    "name": "Lesser Glyph of Mana Regeneration",
    "type": "blue",
    "tier": 1,
    "stat": "mana regeneration",
    "boost": 0.19
  },
  { "id": 5058,
    "name": "Lesser Glyph of Scaling Mana Regeneration",
    "type": "blue",
    "tier": 1,
    "stat": "scaling mana regeneration",
    "boost": 0.04
  },
  { "id": 5059,
    "name": "Lesser Glyph of Magic Penetration",
    "type": "blue",
    "tier": 1,
    "stat": "magic penetration",
    "boost": 0.35
  },
  { "id": 5061,
    "name": "Lesser Seal of Attack Damage",
    "type": "yellow",
    "tier": 1,
    "stat": "attack damage",
    "boost": 0.24
  },
  { "id": 5062,
    "name": "Lesser Seal of Scaling Attack Damage",
    "type": "yellow", 
    "tier": 1,
    "stat": "scaling attack damage",
    "boost": 0.03
  },
  { "id": 5063,
    "name": "Lesser Seal of Attack Speed",
    "type": "yellow",
    "tier": 1,
    "stat": "attack speed",
    "boost": 0.42
  },
  { "id": 5065,
    "name": "Lesser Seal of Critical Damage",
    "type": "yellow",
    "tier": 1,
    "stat": "critical damage",
    "boost": 0.43
  },
  { "id": 5067,
    "name": "Lesser Seal of Critical Chance",
    "type": "yellow",
    "tier": 1,
    "stat": "critical chance",
    "boost": 0.23
  },
  { "id": 5071,
    "name": "Lesser Seal of Health",
    "type": "yellow",
    "tier": 1,
    "stat": "health",
    "boost": 4.48
  },
  { "id": 5072,
    "name": "Lesser Seal of Scaling Health",
    "type": "yellow",
    "tier": 1,
    "stat": "scaling health",
    "boost": 0.75
  },
  { "id": 5073,
    "name": "Lesser Seal of Armor",
    "type": "yellow",
    "tier": 1,
    "stat": "armor",
    "boost": 0.56
  },
  { "id": 5074,
    "name": "Lesser Seal of Scaling Armor",
    "type": "yellow",
    "tier": 1,
    "stat": "scaling armor",
    "boost": 0.09
  },
  { "id": 5075,
    "name": "Lesser Seal of Magic Resist",
    "type": "yellow",
    "tier": 1,
    "stat": "magic resist",
    "boost": 0.41
  },
  { "id": 5076,
    "name": "Lesser Seal of Scaling Magic Resist",
    "type": "yellow",
    "tier": 1,
    "stat": "scaling magic resist",
    "boost": 0.05
  },
  { "id": 5077,
    "name": "Lesser Seal of Health Regeneration",
    "type": "yellow",
    "tier": 1,
    "stat": "health regeneration",
    "boost": 0.31
  },
  { "id": 5078,
    "name": "Lesser Seal of Scaling Health Regeneration",
    "type": "yellow",
    "tier": 1,
    "stat": "scaling health regeneration",
    "boost": 0.06
  },
  { "id": 5081,
    "name": "Lesser Seal of Cooldown Reduction",
    "type": "yellow",
    "tier": 1,
    "stat": "cooldown reduction",
    "boost": -0.2
  },
  { "id": 5083,
    "name": "Lesser Seal of Ability Power",
    "type": "yellow",
    "tier": 1,
    "stat": "ability power",
    "boost": 0.33
  },
  { "id": 5084,
    "name": "Lesser Seal of Scaling Ability Power",
    "type": "yellow",
    "tier": 1,
    "stat": "scaling ability power",
    "boost": 0.06
  },
  { "id": 5085,
    "name": "Lesser Seal of Mana",
    "type": "yellow",
    "tier": 1,
    "stat": "mana",
    "boost": 3.83
  },
  { "id": 5086,
    "name": "Lesser Seal of Scaling Mana",
    "type": "yellow",
    "tier": 1,
    "stat": "scaling mana",
    "boost": 0.65
  },
  { "id": 5087,
    "name": "Lesser Seal of Mana Regeneration",
    "type": "yellow",
    "tier": 1,
    "stat": "mana regeneration",
    "boost": 0.23
  },
  { "id": 5088,
    "name": "Lesser Seal of Scaling Mana Regeneration",
    "type": "yellow",
    "tier": 1,
    "stat": "scaling mana regeneration",
    "boost": 0.036
  },
  { "id": 5091,
    "name": "Lesser Quintessence of Attack Damage",
    "type": "quint",
    "tier": 1,
    "stat": "attack damage",
    "boost": 1.25
  },
  { "id": 5092,
    "name": "Lesser Quintessence of Scaling Attack Damage",
    "type": "quint",
    "tier": 1,
    "stat": "scaling attack damage",
    "boost": 0.14
  },
  { "id": 5093,
    "name": "Lesser Quintessence of Attack Speed",
    "type": "quint",
    "tier": 1,
    "stat": "attack speed",
    "boost": 2.52
  },
  { "id": 5095,
    "name": "Lesser Quintessence of Critical Damage",
    "type": "quint",
    "tier": 1,
    "stat": "critical damage",
    "boost": 2.48
  },
  { "id": 5097,
    "name": "Lesser Quintessence of Critical Chance",
    "type": "quint",
    "tier": 1,
    "stat": "critical chance",
    "boost": 1.03
  },
  { "id": 5099,
    "name": "Lesser Quintessence of Armor Penetration",
    "type": "quint",
    "tier": 1,
    "stat": "armor penetration",
    "boost": 1.42
  },
  { "id": 5101,
    "name": "Lesser Quintessence of Health",
    "type": "quint",
    "tier": 1,
    "stat": "health",
    "boost": 14.5
  },
  { "id": 5102,
    "name": "Lesser Quintessence of Scaling Health",
    "type": "quint",
    "tier": 1,
    "stat": "scaling health",
    "boost": 1.5
  },
  { "id": 5103,
    "name": "Lesser Quintessence of Armor",
    "type": "quint",
    "tier": 1,
    "stat": "armor",
    "boost": 2.37
  },
  { "id": 5104,
    "name": "Lesser Quintessence of Scaling Armor",
    "type": "quint",
    "tier": 1,
    "stat": "scaling armor",
    "boost": 0.21
  },
  { "id": 5105,
    "name": "Lesser Quintessence of Magic Resist",
    "type": "quint",
    "tier": 1,
    "stat": "magic resist",
    "boost": 2.22
  },
  { "id": 5106,
    "name": "Lesser Quintessence of Scaling Magic Resist",
    "type": "quint",
    "tier": 1,
    "stat": "scaling magic resist",
    "boost": 0.21
  },
  { "id": 5107,
    "name": "Lesser Quintessence of Health Regeneration",
    "type": "quint",
    "tier": 1,
    "stat": "health regeneration",
    "boost": 1.5
  },
  { "id": 5108,
    "name": "Lesser Quintessence of Scaling Health Regeneration",
    "type": "quint",
    "tier": 1,
    "stat": "scaling health regeneration",
    "boost": 0.16
  },
  { "id": 5111,
    "name": "Lesser Quintessence of Cooldown Reduction",
    "type": "quint",
    "tier": 1,
    "stat": "cooldown reduction",
    "boost": -1.4
  },
  { "id": 5112,
    "name": "Lesser Quintessence of Scaling Cooldown Reduction",
    "type": "quint",
    "tier": 1,
    "stat": "scaling cooldown reduction",
    "boost": -0.15
  },
  { "id": 5113,
    "name": "Lesser Quintessence of Ability Power",
    "type": "quint",
    "tier": 1,
    "stat": "ability power",
    "boost": 2.75
  },
  { "id": 5114,
    "name": "Lesser Quintessence of Scaling Ability Power",
    "type": "quint",
    "tier": 1,
    "stat": "scaling ability power",
    "boost": 0.24
  },
  { "id": 5115,
    "name": "Lesser Quintessence of Mana",
    "type": "quint",
    "tier": 1,
    "stat": "mana",
    "boost": 20.83
  },
  { "id": 5116,
    "name": "Lesser Quintessence of Scaling Mana",
    "type": "quint",
    "tier": 1,
    "stat": "scaling mana",
    "boost": 2.31
  },
  { "id": 5117,
    "name": "Lesser Quintessence of Mana Regeneration",
    "type": "quint",
    "tier": 1,
    "stat": "mana regeneration",
    "boost": 0.69
  },
  { "id": 5118,
    "name": "Lesser Quintessence of Scaling Mana Regeneration",
    "type": "quint",
    "tier": 1,
    "stat": "scaling mana regeneration",
    "boost": 0.14
  },
  { "id": 5119,
    "name": "Lesser Quintessence of Magic Penetration",
    "type": "quint",
    "tier": 1,
    "stat": "magic penetration",
    "boost": 1.11
  },
  { "id": 5121,
    "name": "Lesser Quintessence of Movement Speed",
    "type": "quint",
    "tier": 1,
    "stat": "movement speed",
    "boost": 0.83
  },
  { "id": 5245,
    "name": "Greater Mark of Attack Damage",
    "type": "red",
    "tier": 3,
    "stat": "attack damage",
    "boost": 0.95
  },
  { "id": 5246,
    "name": "Greater Mark of Scaling Attack Damage",
    "type": "red",
    "tier": 3,
    "stat": "scaling attack damage",
    "boost": 0.13
  },
  { "id": 5247,
    "name": "Greater Mark of Attack Speed",
    "type": "red",
    "tier": 3,
    "stat": "attack speed",
    "boost": 1.7
  },
  { "id": 5249,
    "name": "Greater Mark of Critical Damage",
    "type": "red",
    "tier": 3,
    "stat": "critical damage",
    "boost": 2.23
  },
  { "id": 5251,
    "name": "Greater Mark of Critical Chance",
    "type": "red",
    "tier": 3,
    "stat": "critical chance",
    "boost": 0.93
  },
  { "id": 5253,
    "name": "Greater Mark of Armor Penetration",
    "type": "red",
    "tier": 3,
    "stat": "armor penetration",
    "boost": 1.28
  },
  { "id": 5255,
    "name": "Greater Mark of Health",
    "type": "red",
    "tier": 3,
    "stat": "health",
    "boost": 3.47
  },
  { "id": 5256,
    "name": "Greater Mark of Scaling Health",
    "type": "red",
    "tier": 3,
    "stat": "scaling health",
    "boost": 0.54
  },
  { "id": 5257,
    "name": "Greater Mark of Armor",
    "type": "red",
    "tier": 3,
    "stat": "armor",
    "boost": 0.91
  },
  { "id": 5259,
    "name": "Greater Mark of Magic Resist",
    "type": "red",
    "tier": 3,
    "stat": "magic resist",
    "boost": 0.77
  },
  { "id": 5260,
    "name": "Greater Mark of Scaling Magic Resist",
    "type": "red",
    "tier": 3,
    "stat": "scaling magic resist",
    "boost": 0.07
  },
  { "id": 5265,
    "name": "Greater Mark of Cooldown Reduction",
    "type": "red",
    "tier": 3,
    "stat": "cooldown reduction",
    "boost": -0.2
  },
  { "id": 5267,
    "name": "Greater Mark of Ability Power",
    "type": "red",
    "tier": 3,
    "stat": "ability power",
    "boost": 0.59
  },
  { "id": 5268,
    "name": "Greater Mark of Scaling Ability Power",
    "type": "red",
    "tier": 3,
    "stat": "scaling ability power",
    "boost": 0.1
  },
  { "id": 5269,
    "name": "Greater Mark of Mana",
    "type": "red",
    "tier": 3,
    "stat": "mana",
    "boost": 5.91
  },
  { "id": 5270,
    "name": "Greater Mark of Scaling Mana",
    "type": "red",
    "tier": 3,
    "stat": "scaling mana",
    "boost": 1.17
  },
  { "id": 5271,
    "name": "Greater Mark of Mana Regeneration",
    "type": "red",
    "tier": 3,
    "stat": "mana regeneration",
    "boost": 0.26
  },
  { "id": 5273,
    "name": "Greater Mark of Magic Penetration",
    "type": "red",
    "tier": 3,
    "stat": "magic penetration",
    "boost": 0.87
  },
  { "id": 5275,
    "name": "Greater Glyph of Attack Damage",
    "type": "blue",
    "tier": 3,
    "stat": "Attack Damage",
    "boost": 0.28
  },
  { "id": 5276,
    "name": "Greater Glyph of Scaling Attack Damage",
    "type": "blue",
    "tier": 3,
    "stat": "scaling attack damage",
    "boost": 0.04
  },
  { "id": 5277,
    "name": "Greater Glyph of Attack Speed",
    "type": "blue",
    "tier": 3,
    "stat": "attack speed",
    "boost": 0.64
  },
  { "id": 5279,
    "name": "Greater Glyph of Critical Damage",
    "type": "blue",
    "tier": 3,
    "stat": "critical damage",
    "boost": 0.56
  },
  { "id": 5281,
    "name": "Greater Glyph of Critical Chance",
    "type": "blue",
    "tier": 3,
    "stat": "critical chance",
    "boost": 0.28
  },
  { "id": 5285,
    "name": "Greater Glyph of Health",
    "type": "blue",
    "tier": 3,
    "stat": "health",
    "boost": 2.67
  },
  { "id": 5286,
    "name": "Greater Glyph of Scaling Health",
    "type": "blue",
    "tier": 3,
    "stat": "scaling health",
    "boost": 0.54
  },
  { "id": 5287,
    "name": "Greater Glyph of Armor",
    "type": "blue",
    "tier": 3,
    "stat": "armor",
    "boost": 0.7
  },
  { "id": 5289,
    "name": "Greater Glyph of Magic Resist",
    "type": "blue",
    "tier": 3,
    "stat": "magic resist",
    "boost": 1.34
  },
  { "id": 5290,
    "name": "Greater Glyph of Scaling Magic Resist",
    "type": "blue",
    "tier": 3,
    "stat": "scaling magic resist",
    "boost": 0.16
  },
  { "id": 5291,
    "name": "Greater Glyph of Health Regeneration",
    "type": "blue",
    "tier": 3,
    "stat": "health regeneration",
    "boost": 0.27
  },
  { "id": 5295,
    "name": "Greater Glyph of Cooldown Reduction",
    "type": "blue",
    "tier": 3,
    "stat": "cooldown reduction",
    "boost": -0.83
  },
  { "id": 5296,
    "name": "Greater Glyph of Scaling Cooldown Reduction",
    "type": "blue",
    "tier": 3,
    "stat": "scaling cooldown reduction",
    "boost": -0.09
  },
  { "id": 5297,
    "name": "Greater Glyph of Ability Power",
    "type": "blue",
    "tier": 3,
    "stat": "ability power",
    "boost": 1.19
  },
  { "id": 5298,
    "name": "Greater Glyph of Scaling Ability Power",
    "type": "blue",
    "tier": 3,
    "stat": "scaling ability power",
    "boost": 0.17
  },
  { "id": 5299,
    "name": "Greater Glyph of Mana",
    "type": "blue",
    "tier": 3,
    "stat": "mana",
    "boost": 11.25
  },
  { "id": 5300,
    "name": "Greater Glyph of Scaling Mana",
    "type": "blue",
    "tier": 3,
    "stat": "scaling mana",
    "boost": 1.42
  },
  { "id": 5301,
    "name": "Greater Glyph of Mana Regeneration",
    "type": "blue",
    "tier": 3,
    "stat": "mana regeneration",
    "boost": 0.33
  },
  { "id": 5302,
    "name": "Greater Glyph of Scaling Mana Regeneration",
    "type": "blue",
    "tier": 3,
    "stat": "scaling mana regeneration",
    "boost": 0.06
  },
  { "id": 5303,
    "name": "Greater Glyph of Magic Penetration",
    "type": "blue",
    "tier": 3,
    "stat": "magic penetration",
    "boost": 0.63
  },
  { "id": 5305,
    "name": "Greater Seal of Attack Damage",
    "type": "yellow",
    "tier": 3,
    "stat": "attack damage",
    "boost": 0.43
  },
  { "id": 5306,
    "name": "Greater Seal of Scaling Attack Damage",
    "type": "yellow",
    "tier": 3,
    "stat": "scaling attack damage",
    "boost": 0.06
  },
  { "id": 5307,
    "name": "Greater Seal of Attack Speed",
    "type": "yellow",
    "tier": 3,
    "stat": "attack speed",
    "boost": 0.76
  },
  { "id": 5309,
    "name": "Greater Seal of Critical Damage",
    "type": "yellow",
    "tier": 3,
    "stat": "critical damage",
    "boost": 0.78
  },
  { "id": 5311,
    "name": "Greater Seal of Critical Chance",
    "type": "yellow",
    "tier": 3,
    "stat": "critical chance",
    "boost": 0.42
  },
  { "id": 5315,
    "name": "Greater Seal of Health",
    "type": "yellow",
    "tier": 3,
    "stat": "health",
    "boost": 8
  },
  { "id": 5316,
    "name": "Greater Seal of Scaling Health",
    "type": "yellow",
    "tier": 3,
    "stat": "scaling health",
    "boost": 1.33
  },
  { "id": 5317,
    "name": "Greater Seal of Armor",
    "type": "yellow",
    "tier": 3,
    "stat": "armor",
    "boost": 1
  },
  { "id": 5318,
    "name": "Greater Seal of Scaling Armor",
    "type": "yellow",
    "tier": 3,
    "stat": "scaling armor",
    "boost": 0.16
  },
  { "id": 5319,
    "name": "Greater Seal of Magic Resist",
    "type": "yellow",
    "tier": 3,
    "stat": "magic resist",
    "boost": 0.74
  },
  { "id": 5320,
    "name": "Greater Seal of Scaling Magic Resist",
    "type": "yellow",
    "tier": 3,
    "stat": "scaling magic resist",
    "boost": 0.1
  },
  { "id": 5321,
    "name": "Greater Seal of Health Regeneration",
    "type": "yellow",
    "tier": 3,
    "stat": "health regeneration",
    "boost": 0.56
  },
  { "id": 5322,
    "name": "Greater Seal of Scaling Health Regeneration",
    "type": "yellow",
    "tier": 3,
    "stat": "scaling health regeneration",
    "boost": 0.11
  },
  { "id": 5325,
    "name": "Greater Seal of Cooldown Reduction",
    "type": "yellow",
    "tier": 3,
    "stat": "cooldown reduction",
    "boost": -0.36
  },
  { "id": 5327,
    "name": "Greater Seal of Ability Power",
    "type": "yellow",
    "tier": 3,
    "stat": "ability power",
    "boost": 0.59
  },
  { "id": 5328,
    "name": "Greater Seal of Scaling Ability Power",
    "type": "yellow",
    "tier": 3,
    "stat": "scaling ability power",
    "boost": 0.1
  },
  { "id": 5329,
    "name": "Greater Seal of Mana",
    "type": "yellow",
    "tier": 3,
    "stat": "mana",
    "boost": 6.89
  },
  { "id": 5330,
    "name": "Greater Seal of Scaling Mana",
    "type": "yellow",
    "tier": 3,
    "stat": "scaling mana",
    "boost": 1.17
  },
  { "id": 5331,
    "name": "Greater Seal of Mana Regeneration",
    "type": "yellow",
    "tier": 3,
    "stat": "mana regeneration",
    "boost": 0.41
  },
  { "id": 5332,
    "name": "Greater Seal of Scaling Mana Regeneration",
    "type": "yellow",
    "tier": 3,
    "stat": "scaling mana regeneration",
    "boost": 0.065
  },
  { "id": 5335,
    "name": "Greater Quintessence of Attack Damage",
    "type": "quint",
    "tier": 3,
    "stat": "attack damage",
    "boost": 2.25
  },
  { "id": 5336,
    "name": "Greater Quintessence of Scaling Attack Damage",
    "type": "quint",
    "tier": 3,
    "stat": "scaling attack damage",
    "boost": 0.25
  },
  { "id": 5337,
    "name": "Greater Quintessence of Attack Speed",
    "type": "quint",
    "tier": 3,
    "stat": "attack speed",
    "boost": 4.5
  },
  { "id": 5339,
    "name": "Greater Quintessence of Critical Damage",
    "type": "quint",
    "tier": 3,
    "stat": "critical damage",
    "boost": 4.46
  },
  { "id": 5341,
    "name": "Greater Quintessence of Critical Chance",
    "type": "quint",
    "tier": 3,
    "stat": "critical chance",
    "boost": 1.86
  },
  { "id": 5343,
    "name": "Greater Quintessence of Armor Penetration",
    "type": "quint",
    "tier": 3,
    "stat": "armor penetration",
    "boost": 2.56
  },
  { "id": 5345,
    "name": "Greater Quintessence of Health",
    "type": "quint",
    "tier": 3,
    "stat": "health",
    "boost": 26
  },
  { "id": 5346,
    "name": "Greater Quintessence of Scaling Health",
    "type": "quint",
    "tier": 3,
    "stat": "scaling health",
    "boost": 2.7
  },
  { "id": 5347,
    "name": "Greater Quintessence of Armor",
    "type": "quint",
    "tier": 3,
    "stat": "armor",
    "boost": 4.26
  },
  { "id": 5348,
    "name": "Greater Quintessence of Scaling Armor",
    "type": "quint",
    "tier": 3,
    "stat": "scaling armor",
    "boost": 0.38
  },
  { "id": 5349,
    "name": "Greater Quintessence of Magic Resist",
    "type": "quint",
    "tier": 3,
    "stat": "magic resist",
    "boost": 4
  },
  { "id": 5350,
    "name": "Greater Quintessence of Scaling Magic Resist",
    "type": "quint",
    "tier": 3,
    "stat": "scaling magic resist",
    "boost": 0.37
  },
  { "id": 5351,
    "name": "Greater Quintessence of Health Regeneration",
    "type": "quint",
    "tier": 3,
    "stat": "health regeneration",
    "boost": 2.7
  },
  { "id": 5352,
    "name": "Greater Quintessence of Scaling Health Regeneration",
    "type": "quint",
    "tier": 3,
    "stat": "scaling health regeneration",
    "boost": 0.28
  },
  { "id": 5355,
    "name": "Greater Quintessence of Cooldown Reduction",
    "type": "quint",
    "tier": 3,
    "stat": "cooldown reduction",
    "boost": -2.5
  },
  { "id": 5356,
    "name": "Greater Quintessence of Scaling Cooldown Reduction",
    "type": "quint",
    "tier": 3,
    "stat": "scaling cooldown reduction",
    "boost": -0.28
  },
  { "id": 5357,
    "name": "Greater Quintessence of Ability Power",
    "type": "quint",
    "tier": 3,
    "stat": "ability power",
    "boost": 4.95
  },
  { "id": 5358,
    "name": "Greater Quintessence of Scaling Ability Power",
    "type": "quint",
    "tier": 3,
    "stat": "scaling ability power",
    "boost": 0.43
  },
  { "id": 5359,
    "name": "Greater Quintessence of Mana",
    "type": "quint",
    "tier": 3,
    "stat": "mana",
    "boost": 37.5
  },
  { "id": 5360,
    "name": "Greater Quintessence of Scaling Mana",
    "type": "quint",
    "tier": 3,
    "stat": "scaling mana",
    "boost": 4.17
  },
  { "id": 5361,
    "name": "Greater Quintessence of Mana Regeneration",
    "type": "quint",
    "tier": 3,
    "stat": "mana regeneration",
    "boost": 1.25
  },
  { "id": 5362,
    "name": "Greater Quintessence of Scaling Mana Regeneration",
    "type": "quint",
    "tier": 3,
    "stat": "scaling mana regeneration",
    "boost": 0.24
  },
  { "id": 5363,
    "name": "Greater Quintessence of Magic Penetration",
    "type": "quint",
    "tier": 3,
    "stat": "magic penetration",
    "boost": 2.01
  },
  { "id": 5365,
    "name": "Greater Quintessence of Movement Speed",
    "type": "quint",
    "tier": 3,
    "stat": "movement speed",
    "boost": 1.5
  },
  { "id": 5366,
    "name": "Greater Quintessence of Revival",
    "type": "quint",
    "tier": 3,
    "stat": "time dead",
    "boost": -5
  },
  { "id": 5367,
    "name": "Greater Quintessence of Gold",
    "type": "quint",
    "tier": 3,
    "stat": "gold generation",
    "boost": 1
  },
  { "id": 5368,
    "name": "Greater Quintessence of Experience",
    "type": "quint",
    "tier": 3,
    "stat": "experience gained",
    "boost": 2
  },
  { "id": 5369,
    "name": "Greater Seal of Energy Regeneration",
    "type": "yellow",
    "tier": 3,
    "stat": "energy regeneration",
    "boost": 0.63
  },
  { "id": 5370,
    "name": "Greater Seal of Scaling Energy Regeneration",
    "type": "yellow",
    "tier": 3,
    "stat": "scaling energy regeneration",
    "boost": 0.064
  },
  { "id": 5371,
    "name": "Greater Glyph of Energy",
    "type": "blue",
    "tier": 3,
    "stat": "energy",
    "boost": 2.2
  },
  { "id": 5372,
    "name": "Greater Glyph of Scaling Energy",
    "type": "blue",
    "tier": 3,
    "stat": "scaling energy",
    "boost": 0.161
  },
  { "id": 5373,
    "name": "Greater Quintessence of Energy Regeneration",
    "type": "quint",
    "tier": 3,
    "stat": "energy regeneration",
    "boost": 1.575
  },
  { "id": 5374,
    "name": "Greater Quintessence of Energy",
    "type": "quint",
    "tier": 3,
    "stat": "energy",
    "boost": 5.4
  },
  { "id": 5400,
    "name": "Lesser Mark of Hybrid Penetration",
    "type": "red",
    "tier": 1,
    "stat": "hybrid penetration",
    "boost": [0.5, 0.34]
  },
  { "id": 5401,
    "name": "Mark of Hybrid Penetration",
    "type": "red",
    "tier": 2,
    "stat": "hybrid penetration",
    "boost": [0.7, 0.48]
  },
  { "id": 5402,
    "name": "Greater Mark of Hybrid Penetration",
    "type": "red",
    "tier": 3,
    "stat": "hybrid penetration",
    "boost": [0.9, 0.62]
  },
  { "id": 5403,
    "name": "Greater Seal of Gold",
    "type": "yellow",
    "tier": 3,
    "stat": "gold generation",
    "boost": 0.25
  },
  { "id": 5404,
    "name": "Lesser Quintessence of Percent Health",
    "type": "quint",
    "tier": 1,
    "stat": "percent health",
    "boost": 0.84
  },
  { "id": 5405,
    "name": "Quintessence of Percent Health",
    "type": "quint",
    "tier": 2,
    "stat": "percent health",
    "boost": 1.17
  },
  { "id": 5406,
    "name": "Greater Quintessence of Percent Health",
    "type": "quint",
    "tier": 3,
    "stat": "percent health",
    "boost": 1.5
  },
  { "id": 5407,
    "name": "Lesser Quintessence of Spell Vamp",
    "type": "quint",
    "tier": 1,
    "stat": "spell vamp",
    "boost": 1.12
  },
  { "id": 5408,
    "name": "Quintessence of Spell Vamp",
    "type": "quint",
    "tier": 2,
    "stat": "spell vamp",
    "boost": 1.56
  },
  { "id": 5409,
    "name": "Greater Quintessence of Spell Vamp",
    "type": "quint",
    "tier": 3,
    "stat": "spell vamp",
    "boost": 2
  },
  { "id": 5410,
    "name": "Lesser Quintessence of Life Steal",
    "type": "quint",
    "tier": 1,
    "stat": "life steal",
    "boost": 0.84
  },
  { "id": 5411,
    "name": "Quintessence of Life Steal",
    "type": "quint",
    "tier": 2,
    "stat": "life steal",
    "boost": 1.17
  },
  { "id": 5412,
    "name": "Greater Quintessence of Life Steal",
    "type": "quint",
    "tier": 3,
    "stat": "life steal",
    "boost": 1.5
  },
  { "id": 5413,
    "name": "Lesser Seal of Percent Health",
    "type": "yellow",
    "tier": 1,
    "stat": "percent health",
    "boost": 0.28
  },
  { "id": 5414,
    "name": "Seal of Percent Health",
    "type": "yellow",
    "tier": 2,
    "stat": "percent health",
    "boost": 0.39
  },
  { "id": 5415,
    "name": "Greater Seal of Percent Health",
    "type": "yellow",
    "tier": 3,
    "stat": "percent health",
    "boost": 0.5
  },
  { "id": 5416,
    "name": "Lesser Quintessence of Hybrid Penetration",
    "type": "quint",
    "tier": 1,
    "stat": "hybrid penetration",
    "boost": [0.99, 0.78]
  },
  { "id": 5417,
    "name": "Quintessence of Hybrid Penetration",
    "type": "quint",
    "tier": 2,
    "stat": "hybrid penetration",
    "boost": [1.39, 1.09]
  },
  { "id": 5418,
    "name": "Greater Quintessence of Hybrid Penetration",
    "type": "quint",
    "tier": 3,
    "stat": "hybrid penetration",
    "boost": [1.79, 1.4]
  }
]
  